#define AS_FILE_EXTENSION ".as"
#define ASM_FILE_EXTENSION ".asm"

#define MEMORY_START 100
#define MEMORY_SIZE (1024*12)
#define WORD_SIZE 12
#define MAX_LINE_LENGTH 80
#define MACRO_TABLE_CAPACITY 10