name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name:
        make-check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: make clean
    - name: make
      run: make all

